export type FaqEntry = {
  id: string;
  category: string;
  question: string;
  answer: string;
  /** Mots forts et distinctifs de l'intention (poids fort dans le scoring). */
  keywords: string[];
  /** Formulations naturelles observées ou probables (poids plus faible, renforcent le rappel). */
  variants: string[];
};

export const chatbotFaq: FaqEntry[] = [
  {
    id: "hebergement",
    category: "hebergement",
    keywords: ["loger", "logement", "dormir", "hebergement", "nuit", "nuitee", "chambre", "mazet", "mazets", "couchage", "gite", "heberger"],
    question: "Peut-on loger les participants ?",
    answer:
      "Oui, une soixantaine de personnes dans quinze mazets de deux à six personnes. Comptez 110 à 135 € la nuitée pour un mazet de deux à quatre personnes en formule hôtel, draps, serviettes et ménage final compris, plus la taxe de séjour de 1,30 € par personne de plus de 17 ans et par jour.",
    variants: [
      "peut-on dormir sur place",
      "les invités peuvent-ils dormir sur place",
      "vous avez des logements",
      "il y a des hebergements",
      "mes invités peuvent rester dormir",
      "on peut dormir au domaine",
      "il y a des chambres",
      "combien de personnes peuvent dormir sur place",
      "vous avez combien de couchages",
      "je peux héberger mes invités",
      "on peut loger une cinquantaine de personnes",
      "les gens peuvent rester après la soirée",
      "est-ce qu'on peut dormir après le mariage",
      "je cherche un lieu avec hébergement",
      "vous avez des gites",
      "il y a des mazets",
      "est-ce que les logements sont sur le domaine",
      "je veux éviter que mes invités reprennent la voiture",
      "on sera nombreux vous pouvez héberger tout le monde",
      "ya des logements",
      "combien coute une nuit",
      "combien coute un mazet",
      "quel tarif pour l'hébergement",
      "combien pour dormir",
      "prix nuit",
      "tarif hebergement",
    ],
  },
  {
    id: "pmr",
    category: "accessibilite",
    keywords: ["mobilite", "reduite", "handicap", "pmr", "accessible", "fauteuil"],
    question: "Le domaine est-il accessible aux personnes à mobilité réduite ?",
    answer:
      "Les hébergements sont annoncés accessibles aux personnes à mobilité réduite par le domaine. Pour un besoin précis — cheminement, sanitaires, place de stationnement — appelez avant de réserver afin qu'il soit vérifié sur place.",
    variants: [
      "est-ce adapté aux personnes handicapées",
      "une personne en fauteuil peut-elle venir",
      "les logements sont-ils accessibles en fauteuil",
      "est-ce qu'il y a des sanitaires adaptés",
      "il y a des places pmr",
      "l'accès est-il adapté",
      "je viens avec une personne en fauteuil",
      "est-ce adapté pour quelqu'un qui a des difficultés à marcher",
    ],
  },
  {
    id: "wifi",
    category: "equipements",
    keywords: ["wifi", "internet", "telephone", "television", "connexion", "reseau"],
    question: "Y a-t-il le wifi ?",
    answer:
      "Les mazets sont équipés du wifi, du téléphone et de la télévision. Pour la couverture de la salle de réunion et les équipements de projection, contactez-nous afin de vérifier vos besoins.",
    variants: [
      "vous avez le wifi",
      "il y a internet",
      "le wifi fonctionne-t-il dans les gites",
      "les gites ont-ils internet",
      "est-ce qu'on capte internet",
      "il y a du reseau",
      "vous avez le telephone",
      "les mazets ont-ils la tele",
      "ya le wifi",
      "wifi disponible",
      "internet dans les gites",
    ],
  },
  {
    id: "duree-location",
    category: "location",
    keywords: ["journee", "semaine", "weekend", "week-end", "duree", "vendredi", "dimanche"],
    question: "La salle peut-elle être louée à la journée ou à la semaine ?",
    answer:
      "Oui : à la journée, au week-end ou à la semaine. Le forfait de la grille tarifaire correspond à une journée d'événement ; les autres jours se chiffrent sur devis (voir supplément du lendemain).",
    variants: [
      "peut-on louer pour une journée",
      "on peut louer le week-end",
      "est-ce possible à la semaine",
      "combien de jours peut-on louer",
      "on peut arriver avant",
      "est-ce uniquement à la journée",
      "je voudrais louer plusieurs jours",
      "peut-on rester tout le week-end",
      "est-ce qu'on peut louer du vendredi au dimanche",
      "la location est-elle à la journée",
      "location week-end",
      "location semaine",
      "plusieurs jours",
    ],
  },
  {
    id: "capacite",
    category: "location",
    keywords: ["capacite", "personnes", "invites", "accueillir", "maximum"],
    question: "Quelle est la capacité pour un événement ?",
    answer:
      "La grille tarifaire couvre les groupes jusqu'à 110 personnes, par paliers de 40, 50, 65, 80, 95 et 110 participants. Au-delà, cela est possible en combinant salle, terrasse et chapiteaux, soit devis sur demande.",
    variants: [
      "combien de personnes pouvez-vous accueillir",
      "combien d'invités maximum",
      "on peut être 100",
      "on peut faire un événement de 120 personnes",
      "combien de personnes dans la salle",
      "quelle capacité pour un mariage",
      "on sera 110 c'est possible",
      "on sera plus de 110 c'est possible",
      "vous acceptez combien de personnes",
      "combien de personnes max",
      "capacite salle",
      "nombre maximum d'invités",
      "on sera 80 c'est possible",
    ],
  },
  {
    id: "vaisselle",
    category: "equipements",
    keywords: ["vaisselle", "assiette", "assiettes", "verre", "verres", "couvert", "couverts"],
    question: "La vaisselle est-elle fournie ?",
    answer:
      "En option, de 110 à 150 € selon le nombre de convives : assiettes, verres et couverts. Un inventaire est signé à la prise en charge, et le matériel cassé ou détérioré est remboursé à la restitution des lieux.",
    variants: [
      "est-ce que la vaisselle est comprise",
      "vous fournissez les assiettes",
      "il y a des verres",
      "les couverts sont-ils fournis",
      "peut-on louer la vaisselle",
      "combien coute la vaisselle",
      "la vaisselle est-elle en option",
      "est-ce qu'il faut apporter notre vaisselle",
      "vous avez des assiettes et couverts",
      "prix vaisselle",
      "vaisselle comprise",
      "location vaisselle",
    ],
  },
  {
    id: "soiree-dansante",
    category: "animation",
    keywords: ["danse", "dansante", "sono", "sonorisation", "dj"],
    question: "Peut-on organiser une soirée dansante ?",
    answer: "Oui. La piste de danse dans la salle est prévue pour brancher une sonorisation adaptée au volume des lieux.",
    variants: [
      "peut-on danser",
      "est-ce qu'il y a une piste de danse",
      "on peut organiser une soirée dansante",
      "peut-on mettre de la musique",
      "il y a une piste de danse",
      "peut-on installer un dj",
      "on peut faire venir un dj",
      "la salle est-elle adaptée pour danser",
      "soirée dansante possible",
      "dj possible",
      "musique possible",
    ],
  },
  {
    id: "pluie",
    category: "logistique",
    keywords: ["pluie", "pleut", "pleuvoir", "chapiteau", "chapiteaux", "meteo", "intemperies", "couvert"],
    question: "Que se passe-t-il s'il pleut ?",
    answer:
      "La salle de 90 m² et sa terrasse couverte prennent le relais. Deux chapiteaux de 8 × 4 m (32 personnes chacun) et trois de 4 × 4 m (16 personnes) sont disponibles à 200 € l'unité pour couvrir une partie de la terrasse extérieure, soit 48 personnes.",
    variants: [
      "et s'il pleut",
      "vous avez une solution en cas de pluie",
      "que fait-on si la météo est mauvaise",
      "il y a un espace couvert",
      "peut-on maintenir l'événement s'il pleut",
      "on fait comment en cas de mauvais temps",
      "et si le mariage est sous la pluie",
      "vous avez une salle de repli",
      "il y a des chapiteaux",
      "peut-on couvrir la terrasse",
      "solution pluie",
      "plan b meteo",
      "espace couvert",
    ],
  },
  {
    id: "traiteur",
    category: "restauration",
    keywords: ["traiteur", "impose", "cuisinier", "repas"],
    question: "Faut-il prendre un traiteur imposé ?",
    answer:
      "Non. Ni restauration ni traiteur ne sont imposés. Une cuisine professionnelle de 49 m² est mise à disposition en supplément (200 à 290 € selon le nombre de convives) pour votre traiteur, votre cuisinier à domicile ou vous-même.",
    variants: [
      "peut-on choisir son traiteur",
      "avez-vous un traiteur impose",
      "je peux venir avec mon traiteur",
      "est-ce que le traiteur est libre",
      "on peut cuisiner nous-mêmes",
      "je peux prendre mon propre traiteur",
      "est-ce qu'il faut obligatoirement prendre votre traiteur",
      "peut-on faire appel à un traiteur extérieur",
      "je veux mon traiteur",
      "je connais déjà un traiteur",
      "vous imposez un traiteur",
      "on peut apporter notre propre restauration",
      "peut-on cuisiner sur place",
      "traiteur libre",
      "traiteur impose",
      "notre traiteur possible",
      "je peux ramener mon traiteur",
      "est-ce qu'on peut venir avec notre propre cuisinier",
    ],
  },
  {
    id: "cuisine-equipements",
    category: "equipements",
    keywords: ["cuisine", "frigo", "frigos", "four", "piano", "glacon", "glacons", "congelateur"],
    question: "Comment se compose la grande cuisine professionnelle ?",
    answer:
      "Un espace de 50 m², avec : cinq frigos, deux micro-ondes, deux étuves et un grill, deux brûleurs professionnels avec piano, un grand four à gaz (gaz en bouteille non inclus), une plonge professionnelle avec lave-vaisselle, de nombreuses tables et tablettes en inox, une machine à glaçons (25 kg/24h) et un congélateur.",
    variants: [
      "qu'y a-t-il dans la cuisine",
      "la cuisine est-elle équipée",
      "quels équipements sont disponibles",
      "il y a combien de frigos",
      "il y a un four",
      "vous avez un lave-vaisselle",
      "il y a une machine à glaçons",
      "on peut cuisiner sur place",
      "la cuisine est professionnelle",
      "quelle est la taille de la cuisine",
      "quels équipements sont fournis",
      "cuisine équipée",
      "équipement cuisine",
      "vous avez une cuisine suffisamment équipée pour un traiteur",
    ],
  },
  {
    id: "heure-fin",
    category: "logistique",
    keywords: ["heure", "musique", "bruit", "reglementation"],
    question: "Jusqu'à quelle heure la fête peut-elle durer ?",
    answer:
      "Jusqu'à quatre heures du matin. En cours de soirée, le volume de la musique est baissé et certaines portes et fenêtres sont fermées, pour préserver la tranquillité des résidents et respecter la réglementation sur le bruit.",
    variants: [
      "jusqu'à quelle heure peut-on faire la fête",
      "à quelle heure doit-on arrêter la musique",
      "on peut faire la fête jusqu'à quelle heure",
      "quelle est l'heure de fin",
      "la soirée peut aller jusqu'à 4h",
      "peut-on danser toute la nuit",
      "il y a une limite pour la musique",
      "à quelle heure la musique doit-elle s'arrêter",
      "on peut rester jusqu'à 4 heures",
      "heure maximum",
      "fin de soirée",
      "musique jusqu'à quelle heure",
    ],
  },
  {
    id: "reservation",
    category: "reservation",
    keywords: ["reserver", "reservation", "contrat", "acompte", "arrhes", "caution", "solde"],
    question: "Comment réserve-t-on, et que faut-il prévoir ?",
    answer:
      "La réservation est actée par la signature du contrat et le versement de 50 % du montant total, non remboursables en cas d'annulation. Le solde et une caution de 500 € sont réglés à l'arrivée. Il faut également fournir une attestation de responsabilité civile — votre assureur la délivre gratuitement dans la plupart des cas.",
    variants: [
      "comment réserver",
      "comment faire pour bloquer une date",
      "quelles sont les conditions de réservation",
      "combien faut-il verser pour réserver",
      "quel acompte faut-il payer",
      "il faut payer combien à la réservation",
      "l'acompte est-il remboursable",
      "quelle caution faut-il prévoir",
      "combien est la caution",
      "quand paie-t-on le solde",
      "quels documents faut-il fournir",
      "il faut une assurance",
      "quelle assurance faut-il",
      "attestation responsabilité civile",
      "conditions réservation",
    ],
  },
  {
    id: "menage",
    category: "logistique",
    keywords: ["menage", "nettoyage", "nettoyer"],
    question: "Le ménage de la salle et de la cuisine professionnelle est-il compris ?",
    answer:
      "Non, il est à la charge du locataire. S'il est laissé au domaine, il est facturé 30 € de l'heure selon l'état de la salle, et déduit de la caution.",
    variants: [
      "le ménage est-il compris",
      "qui fait le ménage",
      "combien coûte le ménage",
      "est-ce qu'on doit nettoyer après",
      "je dois nettoyer la salle",
      "le nettoyage est-il inclus",
      "vous pouvez faire le ménage",
      "combien facturez-vous le nettoyage",
      "le ménage de la cuisine est-il compris",
      "ménage inclus",
      "ménage obligatoire",
      "prix ménage",
      "il faut nettoyer après la soirée",
    ],
  },
  {
    id: "distance-adresse",
    category: "localisation",
    keywords: ["adresse", "fayence", "var", "route", "situe", "distance", "cannes", "aeroport", "nice", "km", "grasse", "frejus", "autoroute", "gps"],
    question: "Où se trouve exactement le domaine ?",
    answer:
      "Au 4876 route départementale 562, lieu-dit La Bégude, 83440 Fayence, dans le Var. À 35 km de Grasse, 23 km de Fréjus Saint-Raphaël et 30 km de Cannes, par l'autoroute A8, sorties Les Adrets ou Le Muy.",
    variants: [
      "quelle est votre adresse",
      "où êtes-vous",
      "où se trouve le domaine",
      "c'est dans quelle ville",
      "quelle adresse gps",
      "je dois mettre quoi dans le gps",
      "comment trouver le domaine",
      "vous êtes à fayence",
      "quelle est l'adresse exacte",
      "donnez-moi l'adresse",
      "adresse domaine",
      "vous êtes où",
      "vous êtes loin de cannes",
      "c'est à combien de cannes",
      "combien de kilomètres depuis cannes",
      "quelle distance avec fréjus",
      "c'est loin de nice",
      "l'aéroport de nice est à quelle distance",
      "on est près de grasse",
      "quelle sortie d'autoroute",
      "combien de km de cannes",
      "proche de nice",
      "proche de fréjus",
      "je viens de cannes c'est loin",
    ],
  },
  {
    id: "privatisation",
    category: "location",
    keywords: ["exclusif", "prive", "privee", "privatisation", "seuls"],
    question: "Le domaine est-il privatisé en exclusivité ?",
    answer:
      "Oui, le domaine se privatise en exclusivité pour votre événement, sans autre réception le même jour. La salle, la terrasse et la piste de danse vous sont réservées ; le parc et ses installations restent partagés avec les occupants des mazets, sauf si vous réservez l'ensemble des logements.",
    variants: [
      "est-ce que le domaine est privatisé",
      "est-ce qu'on est seuls",
      "est-ce que les autres clients peuvent être présents",
      "la salle est-elle privée",
      "le parc est-il privé",
      "est-ce que tout le domaine nous appartient",
      "peut-on avoir l'ensemble du domaine",
      "les logements sont-ils partagés",
      "est-ce qu'il y aura d'autres personnes",
      "on est seuls pendant l'événement",
      "domaine privatisé",
      "salle privatisée",
      "parc privé",
      "je voudrais louer tout le domaine est-ce que les autres personnes seront là",
    ],
  },
  {
    id: "ceremonie-parc",
    category: "animation",
    keywords: ["ceremonie", "laique", "vin", "honneur", "cocktail", "defile", "apero", "apéritif"],
    question: "Peut-on organiser la cérémonie dans le parc paysager ?",
    answer:
      "Oui. Le parc paysager et la terrasse se prêtent à une cérémonie laïque, à un vin d'honneur, à un spectacle, à un apéritif dinatoire ou à un défilé. La terrasse de 90 m² est comprise dans le forfait salle.",
    variants: [
      "peut-on faire la cérémonie dehors",
      "peut-on se marier dans le parc",
      "est-ce possible de faire une cérémonie laïque",
      "peut-on faire la cérémonie sur place",
      "on peut faire un vin d'honneur dehors",
      "peut-on organiser un apéritif dans le parc",
      "le parc est-il disponible pour la cérémonie",
      "est-ce qu'on peut faire la cérémonie extérieure",
      "cérémonie laïque possible",
      "cérémonie dehors",
      "mariage dans le parc",
      "est-ce qu'on peut faire une cérémonie dehors",
    ],
  },
  {
    id: "decoration-veille",
    category: "logistique",
    keywords: ["decorer", "decoration", "veille", "installer"],
    question: "Peut-on venir décorer la veille ?",
    answer:
      "Oui. La salle est à votre disposition la veille ou l'avant-veille de l'événement, de 9 h à 19 h, pour approvisionner les réfrigérateurs et installer votre décoration.",
    variants: [
      "peut-on venir avant le mariage",
      "peut-on préparer la salle la veille",
      "est-ce qu'on peut installer la décoration avant",
      "peut-on accéder à la salle la veille",
      "on peut venir installer les décorations",
      "à quelle heure peut-on venir décorer",
      "peut-on venir l'avant-veille",
      "est-ce qu'on peut mettre les décorations avant",
      "installation décoration",
      "accès veille",
      "je peux installer mes décorations la veille",
      "on peut décorer la veille",
    ],
  },
  {
    id: "enfants",
    category: "animation",
    keywords: ["enfant", "enfants", "jeux", "boules", "volley", "football", "piscine"],
    question: "Les enfants ont-ils de quoi s'occuper ?",
    answer:
      "Le domaine dispose d'une aire de jeux pour enfants, d'un terrain de boules, de volley et de football. La piscine est accessible en option le lendemain uniquement, de 9 h à 20 h ; elle n'est pas surveillée et les moins de quinze ans doivent être accompagnés d'un adulte — un règlement est affiché sur place.",
    variants: [
      "il y a des jeux pour les enfants",
      "les enfants peuvent-ils s'amuser",
      "vous avez une aire de jeux",
      "il y a une piscine",
      "la piscine est-elle accessible",
      "les enfants peuvent-ils aller à la piscine",
      "il y a du football",
      "il y a un terrain de volley",
      "il y a des activités pour les enfants",
      "activités enfants",
      "jeux enfants",
      "aire de jeux",
      "mes enfants pourront faire quoi pendant la réception",
    ],
  },
  {
    id: "climatisation",
    category: "equipements",
    keywords: ["climatise", "climatisation", "clim"],
    question: "Les gîtes sont-ils climatisés ?",
    answer: "Oui. La salle peut également l'être, à condition que les portes et fenêtres restent bien fermées.",
    variants: [
      "les gites ont-ils la climatisation",
      "les mazets sont-ils climatisés",
      "est-ce climatisé",
      "on peut dormir au frais",
      "climatisation gites",
      "clim dans les mazets",
      "la salle est-elle climatisée",
      "il y a la clim dans la salle",
      "est-ce qu'on peut climatiser la salle",
      "la salle possède-t-elle la climatisation",
      "est-ce qu'il fera frais dans la salle",
      "climatisation salle",
      "salle climatisée",
      "et la salle elle est climatisée",
    ],
  },
  {
    id: "tri-dechets",
    category: "logistique",
    keywords: ["tri", "poubelle", "poubelles", "dechets", "recyclage", "compost"],
    question: "Que deviennent vos poubelles ?",
    answer:
      "Les différentes poubelles de tri sont à votre disposition. Poubelle jaune = tous les emballages. Poubelle marron = déchets ménagers. Poubelle verte = le verre. Poubelle compost = déchets de légumes. Poubelle carton = carton à plat. Le tri est un sujet important : s'il n'est pas respecté durant le séjour, la caution peut être retenue en intégralité et les autorités compétentes peuvent être informées.",
    variants: [
      "comment fonctionne le tri",
      "où jeter les déchets",
      "quelles sont les poubelles",
      "il faut trier les déchets",
      "quelle poubelle pour les emballages",
      "où mettre le verre",
      "où mettre le carton",
      "où mettre les déchets alimentaires",
      "est-ce qu'il y a un compost",
      "que doit-on faire des poubelles",
      "tri déchets",
      "poubelle jaune",
      "poubelle verte",
      "poubelle compost",
      "poubelle carton",
    ],
  },
  {
    id: "seminaire",
    category: "evenement",
    keywords: ["seminaire", "entreprise", "reunion", "teambuilding"],
    question: "Organisez-vous des séminaires d'entreprise ?",
    answer: "Oui, le domaine accueille séminaires, réunions et journées de team building avec salles équipées et hébergement sur place.",
    variants: ["vous accueillez des entreprises", "on peut faire un séminaire", "vous faites du team building", "réunion d'entreprise possible"],
  },
  {
    id: "animaux",
    category: "logistique",
    keywords: ["animal", "animaux", "chien", "chiens", "chat", "chats"],
    question: "Les animaux sont-ils acceptés lors de l'événement ?",
    answer: "Malheureusement, les animaux (y compris les chiens) ne sont plus acceptés lors des événements.",
    variants: [
      "peut-on venir avec notre chien",
      "les chiens sont-ils autorisés",
      "on peut amener un animal de compagnie",
      "les animaux sont-ils admis",
      "acceptez-vous les chiens",
    ],
  },
  {
    id: "devis",
    category: "reservation",
    keywords: ["devis", "contact", "disponibilite", "disponibilites"],
    question: "Comment obtenir un devis ?",
    answer: "Remplissez le formulaire de la page Contact avec votre date et le nombre d'invités : nous revenons vers vous sous 48h.",
    variants: ["comment vous contacter", "je veux un devis", "vous êtes disponibles à quelle date", "comment avoir un prix personnalisé"],
  },
];
